version: '4.54.0'

services:

  mongo:
    image: mongo:6
    container_name: mongo-COGO
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cogoDB
    volumes:
      - cogo_mongo_data:/data/db

volumes:
  cogo_mongo_data:
